<?xml version="1.0"?>
<robot name="jr">
  <link name="base_footprint" />
  <joint name="base_footprint_to_base_link" type="fixed">
    <parent link="base_footprint" />
    <child link="base_link" />
    <origin xyz="0 0 0.0587375" rpy="0 0 0"/>
    <axis xyz="0 0 0" />
  </joint>

  <include filename="$(find jr_description)/urdf/jr_description.urdf" />

  <include filename="$(find jr_description)/urdf/arm.xacro" />
  <turtlebot_arm parent="arm_base" color="white" gripper_color="green">
    <origin xyz="0 0 ${AX12_WIDTH/2}"/>
  </turtlebot_arm>
</robot>
